[changelog]
header = """
# Changelog
"""

body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim }}

{% for commit in commits %}
- {{ commit.message | upper_first }}{% if commit.breaking %} **💥 BREAKING CHANGE**{% endif %}
{% endfor %}
{% endfor %}
"""

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false

commit_parsers = [
    { message = "^feat", group = "🚀 Features" },
    { message = "^fix", group = "🐛 Bug Fixes" },
    { message = "^perf", group = "⚡ Performance" },
    { message = "^refactor", group = "♻️ Refactoring" },
    { message = "^docs", group = "📚 Documentation" },
    { message = "^test", group = "🧪 Tests" },
    { message = "^build", group = "📦 Build" },
    { message = "^ci", group = "🔧 CI" },
    { message = "^chore", skip = true },
]

tag_pattern = "v[0-9].*"